Merge Branch-RefactorAddCommand Hong Liang into Master
AY2223S1-CS2103-F09-2/tp pull request #102
Opened 2022-10-19 16:31 UTC by tanhl2000

closes #76

2022-10-21 02:07 UTC, Qiaoran-M requested changes
LGTM except minor issues!

2022-10-21 02:07 UTC, Qiaoran-M commented on src/main/java/seedu/address/logic/commands/AddPersonCommand.java
>      public static final String COMMAND_WORD = "add";
You can change the command word here
```suggestion
    public static final String COMMAND_WORD = "addPerson";
```

2022-10-21 02:07 UTC, Qiaoran-M commented on src/test/java/seedu/address/testutil/PersonUtil.java
>      public static String getAddCommand(Person person) {
you can change the method signature to `getAddPersonCommand` as well.
```suggestion
    public static String getAddPersonCommand(Person person) {
```

2022-10-23 08:48 UTC, tanhl2000 commented on src/main/java/seedu/address/logic/commands/AddPersonCommand.java
>      public static final String COMMAND_WORD = "add";
ok will do!

2022-10-23 08:49 UTC, tanhl2000 commented on src/test/java/seedu/address/testutil/PersonUtil.java
>      public static String getAddCommand(Person person) {
thanks for catching!

2022-10-25 01:43 UTC, Qiaoran-M approved these changes
LGTM!

2022-10-25 18:03 UTC, merged