Add findEvents command
AY2223S1-CS2103-F09-2/tp pull request #128
Opened 2022-10-24 12:17 UTC by lfrostbytee

Currently, the Duke The Market application supports the Event class which is similar to the Person class.

As there may be multiple events, it is crucial to implement a similar findPersons feature like findEvents to help the user locate events more easily.

Let's,
* Add a new FindEventsCommand.java
* Add a new FindEventsCommandParser.java
* Add a new EventTitleContainsKeywordsPredicate.java
* Update Messages.java and AddressBookParser.java

Closes #85

2022-10-25 10:05 UTC, Vinodjayakumar124 requested changes
Look good! Just some minor changes required

2022-10-25 10:05 UTC, Vinodjayakumar124 commented on src/main/java/seedu/address/commons/core/Messages.java
>      public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d persons listed!";
This change may be helpful when there's only 1 event/ 1 person listed
```suggestion
    public static final String MESSAGE_EVENTS_LISTED_OVERVIEW = "%1$d event(s) listed!";
    public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d person(s) listed!";
```

2022-10-25 10:05 UTC, Vinodjayakumar124 commented on src/main/java/seedu/address/logic/parser/FindEventsCommandParser.java
> + * Parses input arguments and creates a new FindEventsCommand object
Just a missing fullstop
```suggestion
 * Parses input arguments and creates a new FindEventsCommand object.
```

2022-10-25 10:05 UTC, Vinodjayakumar124 commented on src/main/java/seedu/address/logic/parser/FindEventsCommandParser.java
> +     * @throws ParseException if the user input does not conform the expected format
Just a missing fullstop here
```suggestion
     * @throws ParseException if the user input does not conform the expected format.
```

2022-10-25 10:05 UTC, Vinodjayakumar124 commented on src/main/java/seedu/address/model/event/EventTitleContainsKeywordsPredicate.java
> +    //TODO: StringUtil.containsWordIgnoreCase(event.getEventTitle().fullEventTitle, kewyord));
Using toString() might be a better option so we don't directly access the attributes of EventTitle class though I'm aware that it's a public attribute at the moment
```suggestion
    //TODO: StringUtil.containsWordIgnoreCase(event.getEventTitle().toString(), kewyord));
```

2022-10-26 06:14 UTC, lfrostbytee commented on src/main/java/seedu/address/commons/core/Messages.java
>      public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d persons listed!";
Ah I like this change. Nice suggestion!

2022-10-26 11:41 UTC, Vinodjayakumar124 approved these changes
Just 1 suggestion to consider!

2022-10-26 11:41 UTC, Vinodjayakumar124 commented on src/main/java/seedu/address/model/event/EventTitleContainsKeywordsPredicate.java
> +    }
My EventTitle class will likely be merged before yours, so actually do you want to just replace this now 
```suggestion
    //TODO: StringUtil.containsWordIgnoreCase(event.getEventTitle().toString(), kewyord));
    @Override
    public boolean test(Event event) {
        return keywords.stream()
                .anyMatch(keyword -> StringUtil.containsWordIgnoreCase(event.getEventTitle().toString(), keyword));
    }
```

2022-10-27 04:42 UTC, merged