Merge Branch-UG3 Hong Liang with master
AY2223S1-CS2103-F09-2/tp pull request #206
Opened 2022-10-31 07:39 UTC by tanhl2000

closes #156, #162, #182

2022-11-01 05:26 UTC, Qiaoran-M requested changes
LGTM except for minor changes 👍

2022-11-01 05:26 UTC, Qiaoran-M commented on docs/UserGuide.md
>  edits gender to be `Female` and edits date of birth to be `3.4.1998`.
```suggestion
edits gender to be `Female` and edits date of birth to be `3/4/1998`.
```

2022-11-01 05:26 UTC, Qiaoran-M commented on docs/UserGuide.md
>  - Date format accepted is: dd/mm/yyyy.
```suggestion
- Date format accepted is: `dd/mm/yyyy`.
```

2022-11-01 05:26 UTC, Qiaoran-M commented on docs/UserGuide.md
>  - Date format accepted is: dd/mm/yyyy.
```suggestion
- Date format accepted is: `dd/mm/yyyy`.
```

2022-11-01 08:56 UTC, tanhl2000 commented on docs/UserGuide.md
>  edits gender to be `Female` and edits date of birth to be `3.4.1998`.
thx for catching

2022-11-01 08:56 UTC, tanhl2000 commented on docs/UserGuide.md
>  - Date format accepted is: dd/mm/yyyy.
will change

2022-11-02 13:45 UTC, Qiaoran-M requested changes
All good except for 1 minor change 👍

2022-11-02 13:45 UTC, Qiaoran-M commented on docs/UserGuide.md
> +* The `INDEX` must be a positive integer 1, 2, 3, …, and it must be within the range of the event list index.
This line overwrites the previous PR changes about invalid index.
```suggestion
* The `INDEX` must be **a positive integer** 1, 2, 3, …, and it must be within the range of the event list index. This command is invalid if `EVENT_INDEX` is a non-positive integer.
```

2022-11-03 07:08 UTC, tanhl2000 commented on docs/UserGuide.md
> +* The `INDEX` must be a positive integer 1, 2, 3, …, and it must be within the range of the event list index.
ah my mistake ok will change

2022-11-03 07:16 UTC, Qiaoran-M approved these changes
LGTM!

2022-11-03 07:16 UTC, merged