Merge Branch-FutureDateCheck Hong Liang with master
AY2223S1-CS2103-F09-2/tp pull request #222
Opened 2022-11-03 11:33 UTC by tanhl2000

closes #149

2022-11-03 13:25 UTC, Qiaoran-M requested changes
LGTM except for minor changes 👍
You might want to add in the `isAfterCurrentDate()` check before the line `final Date modelDob = new Date(dob);` in `toModelType` method in `JsonAdaptedPerson` class.

2022-11-03 13:25 UTC, Qiaoran-M commented on docs/UserGuide.md
> +- Date cannot be after the current date.
```suggestion
- Date of birth cannot be after the current date.
```

2022-11-03 13:25 UTC, Qiaoran-M commented on docs/UserGuide.md
> +- Date cannot be after the current date.
```suggestion
- Date of birth cannot be after the current date.
```

2022-11-03 13:25 UTC, Qiaoran-M commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
>       * Leading and trailing whitespaces will be trimmed.
I think it might be better to explain in the header comment the input parameter `isFutureDateAllowed`

2022-11-04 03:45 UTC, tanhl2000 commented on docs/UserGuide.md
> +- Date cannot be after the current date.
thanks for catching will change

2022-11-04 03:45 UTC, tanhl2000 commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
>       * Leading and trailing whitespaces will be trimmed.
yup will explain!

2022-11-04 14:11 UTC, Qiaoran-M approved these changes
LGTM!

2022-11-04 14:12 UTC, merged