merge Branch-MakeStats-TestSuite Hong Liang with master
AY2223S1-CS2103-F09-2/tp pull request #234
Opened 2022-11-06 06:32 UTC by tanhl2000

closes #223

2022-11-06 15:38 UTC, Qiaoran-M requested changes
Very nice test suite implementation! only a few minor changes needed

2022-11-06 15:38 UTC, Qiaoran-M commented on src/main/java/seedu/address/logic/commands/MakeStatsCommand.java
> +    public static final String INDEX_OUT_OF_BOUNDS_MESSAGE = "Event index given is out of event list range.";
This message is in the `Messages` class already and you can directly use it from there

2022-11-06 15:38 UTC, Qiaoran-M commented on src/main/java/seedu/address/logic/commands/MakeStatsCommand.java
> +            throw new CommandException(INDEX_OUT_OF_BOUNDS_MESSAGE);
```suggestion
            throw new CommandException(Messages.MESSAGE_INVALID_EVENT_DISPLAYED_INDEX);
```

2022-11-06 15:38 UTC, Qiaoran-M commented on src/main/java/seedu/address/logic/commands/MakeStatsCommand.java
> +
I think it's better to move the `equals` method to the end of this class (below all other methods) for consistency with other command classes

2022-11-06 15:38 UTC, Qiaoran-M commented on src/test/java/seedu/address/model/statistics/StatisticsDataListTest.java
> +        modelDataList.addStatistic(new StatisticData(TEST_NAME, 1.0));
```suggestion
        modelDataList.addStatistic(new StatisticData(TEST_NAME, TEST_VALUE));
```

2022-11-06 15:38 UTC, Qiaoran-M commented on src/test/java/seedu/address/model/statistics/StatisticsDataListTest.java
> +        ////StatisticDataList contains the specified StatisticData
```suggestion
        //StatisticDataList contains the specified StatisticData
```

2022-11-06 15:38 UTC, Qiaoran-M commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +    public static final String STATS_DESC_GENDER = " " + PREFIX_TYPE + VALID_GENDER_TYPE;
```suggestion
    public static final String TYPE_DESC_GENDER = " " + PREFIX_TYPE + VALID_GENDER_TYPE;
```

2022-11-06 15:38 UTC, Qiaoran-M commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +    public static final String STATS_DESC_AGE = " " + PREFIX_TYPE + VALID_AGE_TYPE;
```suggestion
    public static final String TYPE_DESC_AGE = " " + PREFIX_TYPE + VALID_AGE_TYPE;
```

2022-11-06 15:38 UTC, Qiaoran-M commented on src/test/java/seedu/address/logic/commands/MakeStatsCommandTest.java
> +                model, MakeStatsCommand.INDEX_OUT_OF_BOUNDS_MESSAGE);
Same as above
```suggestion
                model, Messages.MESSAGE_INVALID_EVENT_DISPLAYED_INDEX);
```

2022-11-07 03:03 UTC, tanhl2000 commented on src/main/java/seedu/address/logic/commands/MakeStatsCommand.java
> +    public static final String INDEX_OUT_OF_BOUNDS_MESSAGE = "Event index given is out of event list range.";
ok will change!

2022-11-07 03:04 UTC, tanhl2000 commented on src/main/java/seedu/address/logic/commands/MakeStatsCommand.java
> +
ah ok will change!

2022-11-07 03:05 UTC, tanhl2000 commented on src/test/java/seedu/address/model/statistics/StatisticsDataListTest.java
> +        modelDataList.addStatistic(new StatisticData(TEST_NAME, 1.0));
thx for catching!

2022-11-07 03:05 UTC, tanhl2000 commented on src/test/java/seedu/address/model/statistics/StatisticsDataListTest.java
> +        ////StatisticDataList contains the specified StatisticData
will change

2022-11-07 03:07 UTC, tanhl2000 commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +    public static final String STATS_DESC_GENDER = " " + PREFIX_TYPE + VALID_GENDER_TYPE;
will change

2022-11-07 03:08 UTC, tanhl2000 commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +    public static final String STATS_DESC_AGE = " " + PREFIX_TYPE + VALID_AGE_TYPE;
will change!

2022-11-07 05:10 UTC, Qiaoran-M approved these changes
LGTM!

2022-11-07 05:11 UTC, merged