Branch improve event date and time v1.3
AY2223S1-CS2103-F09-2/tp pull request #74
Opened 2022-10-15 12:24 UTC by lfrostbytee

Currently, the application Duke The Market only supports Event Date and Time fields as Strings.
To increase the functionality of the application, we can save these fields as LocalDate and LocalTime objects instead.

Closes #68

2022-10-15 14:07 UTC, Benjamin-Sim requested changes
Mostly good except for some issues with `StartDate` and `StartTime`.

I can see that you copy-pasted `StartDate` and `StartTime` from `DateOfBirth` 😆

But there are some aspects of `DateOfBirth` which may not fit the purpose of `StartDate` and `StartTime`. E.g. `DateOfBirth` is optional but `StartDate` and `StartTime` are not. So perhaps the `isEmpty` field and the logic to manipulate it should be removed?

For the code quality issues, it's my fault that I didn't catch them when reviewing `DateOfBirth`. So some of the changes I've suggested also need to be replicated in `DateOfBirth`. 😭 But I can do them since I'll modify `DateOfBirth` when I implement sorting by DOB.

On a side note, since some parts of `StartDate` and `DateOfBirth` are very similar, do you think they should be abstracted out to a separate class?

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartDate.java
> +    }
I don't think this is how the `compareTo()` method should be written. The class should implement the `Comparable<T>` interface, which specifies that `compareTo()` takes in an object of the same class. Hence, there won't be a need to check if the given object is an instance of `StartDate` etc.

You can remove this method for now. I will add it in again when implementing sort by date.

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartDate.java
> +            throw new IllegalArgumentException(MESSAGE_ARGUMENT_CONSTRAINTS);
`MESSAGE_ARGUMENT_CONSTRAINTS` is inappropriate here since this method is `equals()`, not `compareTo()`.

In fact, I don't think this is how `equals()` should be written, given how it is designed in other classes. Looks like it was copy-pasted from `compareTo()`. Also I don't believe `equals()` should throw any exceptions! 😆

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartDate.java
> +            "compareTo() of StartDate must take in argument of type LocalDate";
If it's not used in the `compareTo()` method, it can be removed

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartDate.java
> +     * "" empty string is used to represent an empty StartDate.
Empty string is not a valid `StartDate`

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartTime.java
> +     * "" empty string is used to represent an empty StartTime.
Empty string is not a valid `StartTime`

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartTime.java
> +    }
Same comment as `compareTo()` in `StartDate`

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartTime.java
> +            throw new IllegalArgumentException(MESSAGE_ARGUMENT_CONSTRAINTS);
Same comment as `equals()` in `StartDate`

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartTime.java
> +            "compareTo() of StartTime must take in argument of type LocalTime";
If it's not used in the `compareTo()` method, it can be removed

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartDate.java
> +    }
Is this used anywhere? If not can remove it

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartTime.java
> +    }
Is this used anywhere? If not can remove it

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartDate.java
> +        }
Are you sure `null` is a valid `StartDate` since `StartDate` is a mandatory field?

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartTime.java
> +        }
Are you sure `null` is a valid `StartTime` since `StartTime` is a mandatory field?

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartDate.java
> +    private boolean isEmpty;
Since `StartDate` is a mandatory field, is there a need to have `isEmpty` since there shouldn't be any empty start dates?

2022-10-15 14:07 UTC, Benjamin-Sim commented on src/main/java/seedu/address/model/event/StartTime.java
> +    private boolean isEmpty;
Since `StartTime` is a mandatory field, is there a need to have `isEmpty` since there shouldn't be any empty start times?

2022-10-18 03:47 UTC, Benjamin-Sim approved these changes
LGTM! 👍

2022-10-18 06:07 UTC, Vinodjayakumar124 approved these changes
LGTM! Couldn't find any issues with this before n after lunch

2022-10-18 06:08 UTC, merged